"""Generated by backtest-runner skill from specs/funding-rate-extreme-mr.yaml v0.1.0.

Strategy: take the unpopular side of a perp when funding rate hits historical
extreme percentile; exit on time or stop-loss. Uses funding payments as carry.

NOTE: This module avoids vectorbt as a hard dependency so unit tests can run
in minimal environments. A vectorbt wrapper lives in
`strategies/_vectorbt_adapter.py` (created in Phase 4 once vectorbt is installed).
"""
from __future__ import annotations
from dataclasses import dataclass

import numpy as np
import pandas as pd

IN_SAMPLE_END = pd.Timestamp("2022-12-31", tz="UTC")


@dataclass
class Params:
    lookback_hours: int = 720
    upper_percentile: float = 0.95
    lower_percentile: float = 0.05
    holding_bars: int = 16


def compute_thresholds(funding: pd.Series, p: Params) -> pd.DataFrame:
    """Rolling percentile thresholds. All .shift(1) to prevent lookahead."""
    upper = (
        funding.rolling(p.lookback_hours, min_periods=p.lookback_hours // 2)
        .quantile(p.upper_percentile)
        .shift(1)
    )
    lower = (
        funding.rolling(p.lookback_hours, min_periods=p.lookback_hours // 2)
        .quantile(p.lower_percentile)
        .shift(1)
    )
    return pd.DataFrame({"upper": upper, "lower": lower})


def generate_signals(df: pd.DataFrame, p: Params) -> pd.Series:
    """Returns Series of {-1, 0, +1} = {short_entry, hold/flat, long_entry}.
    Signal at t means: at next bar's open, take this position.
    """
    funding = df["funding_rate"].fillna(0)
    th = compute_thresholds(funding, p)
    f_prev = funding.shift(1)
    sig = pd.Series(0, index=df.index, dtype="int8")
    sig[f_prev >= th["upper"]] = -1
    sig[f_prev <= th["lower"]] = +1
    return sig


def simulate(
    df: pd.DataFrame,
    p: Params,
    *,
    fee: float = 0.0005,
    slippage: float = 0.0005,
    stop_loss_pct: float = 0.04,
    position_fraction: float = 0.10,
    init_cash: float = 100_000.0,
    in_sample_only: bool = True,
) -> dict:
    """Minimal event-loop simulator (slow but transparent for unit testing).

    For Phase 4 production runs use the vectorbt adapter — this function is
    primarily for reproducible unit tests with known input/output.
    """
    if in_sample_only:
        assert df.index.max() <= IN_SAMPLE_END, (
            f"OOS leakage: df ends {df.index.max()} > {IN_SAMPLE_END}"
        )

    sig = generate_signals(df, p)
    open_px = df["open"].to_numpy()
    close_px = df["close"].to_numpy()
    funding = df["funding_rate"].fillna(0).to_numpy()
    sig_arr = sig.to_numpy()

    cash = init_cash
    pos_side = 0          # -1, 0, +1
    pos_qty = 0.0         # in base ccy
    entry_idx = -1
    entry_px = 0.0
    trades: list[dict] = []

    for i in range(1, len(df)):
        # accrue funding on existing position (perp convention: long pays positive funding)
        if pos_side != 0 and funding[i] != 0:
            cash -= pos_side * pos_qty * close_px[i] * funding[i]

        # exit conditions
        if pos_side != 0:
            held = i - entry_idx
            # stop loss
            unrealized_pct = pos_side * (close_px[i] - entry_px) / entry_px
            time_exit = held >= p.holding_bars
            sl_exit = unrealized_pct <= -stop_loss_pct
            if time_exit or sl_exit:
                fill_px = open_px[i] * (1 + pos_side * slippage)
                pnl = pos_side * (fill_px - entry_px) * pos_qty
                cash += pnl - abs(pos_qty * fill_px) * fee
                trades.append({
                    "entry_idx": entry_idx, "exit_idx": i,
                    "side": pos_side, "entry_px": entry_px, "exit_px": fill_px,
                    "pnl": pnl, "reason": "sl" if sl_exit else "time",
                })
                pos_side, pos_qty, entry_idx, entry_px = 0, 0.0, -1, 0.0

        # entries (use signal at i-1, fill at open[i])
        if pos_side == 0 and sig_arr[i - 1] != 0:
            side = int(sig_arr[i - 1])
            fill_px = open_px[i] * (1 - side * slippage)
            notional = cash * position_fraction
            qty = notional / fill_px
            cash -= abs(qty * fill_px) * fee
            pos_side, pos_qty, entry_idx, entry_px = side, qty, i, fill_px

    # mark-to-market final equity
    final_mtm = cash + pos_side * pos_qty * (close_px[-1] - entry_px) if pos_side else cash
    return {
        "final_equity": float(final_mtm),
        "total_return": float(final_mtm / init_cash - 1),
        "trade_count": len(trades),
        "trades": trades,
    }
