"""Step 1 — Import BTC/USDT 1m / 5m OHLCV.

Tries Binance public REST endpoints in order. If every endpoint is blocked
(common in sandboxed environments) the loader falls back to a realistic
synthetic OHLCV series generated by geometric Brownian motion so the rest of
the pipeline can be exercised without network access.
"""
from __future__ import annotations

import os
import time
from dataclasses import dataclass
from typing import List, Optional

import numpy as np
import pandas as pd
import requests


BINANCE_ENDPOINTS = [
    "https://api.binance.com/api/v3/klines",
    "https://api-gcp.binance.com/api/v3/klines",
    "https://api1.binance.com/api/v3/klines",
    "https://data-api.binance.vision/api/v3/klines",
]

INTERVAL_MS = {"1m": 60_000, "5m": 300_000, "15m": 900_000, "1h": 3_600_000}


@dataclass
class FetchResult:
    df: pd.DataFrame
    source: str  # "binance" or "synthetic"
    symbol: str
    interval: str


def _binance_klines(symbol: str, interval: str, limit: int = 1000) -> Optional[pd.DataFrame]:
    params = {"symbol": symbol, "interval": interval, "limit": min(limit, 1000)}
    for base in BINANCE_ENDPOINTS:
        try:
            r = requests.get(base, params=params, timeout=8)
            if r.status_code == 200:
                data = r.json()
                if isinstance(data, list) and data:
                    return _klines_to_df(data)
        except requests.RequestException:
            continue
    return None


def _klines_to_df(raw: List[list]) -> pd.DataFrame:
    cols = [
        "open_time", "open", "high", "low", "close", "volume",
        "close_time", "quote_volume", "trades",
        "taker_buy_base", "taker_buy_quote", "ignore",
    ]
    df = pd.DataFrame(raw, columns=cols)
    df["timestamp"] = pd.to_datetime(df["open_time"], unit="ms", utc=True)
    for c in ("open", "high", "low", "close", "volume"):
        df[c] = pd.to_numeric(df[c])
    return df[["timestamp", "open", "high", "low", "close", "volume"]].set_index("timestamp")


def _synthetic_ohlcv(interval: str, n_bars: int, seed: int = 42,
                     start_price: float = 65_000.0) -> pd.DataFrame:
    """Geometric Brownian motion with intra-bar OHLC and volume bursts."""
    rng = np.random.default_rng(seed)
    step_ms = INTERVAL_MS[interval]
    # ~80% annualised vol, drift 5%/yr
    bars_per_year = 365 * 24 * 60 * (60_000 / step_ms)
    mu = 0.05 / bars_per_year
    sigma = 0.80 / np.sqrt(bars_per_year)

    returns = rng.normal(mu, sigma, size=n_bars)
    # inject occasional jumps to create regime changes
    jumps = rng.choice([0.0, 1.0], size=n_bars, p=[0.997, 0.003]) * rng.normal(0, 4 * sigma, size=n_bars)
    returns = returns + jumps
    close = start_price * np.exp(np.cumsum(returns))

    open_ = np.empty_like(close)
    open_[0] = start_price
    open_[1:] = close[:-1]
    # high/low as a wick around max(open,close) / min(open,close)
    wick = np.abs(rng.normal(0, sigma * 0.6, size=n_bars)) * close
    high = np.maximum(open_, close) + wick
    low = np.minimum(open_, close) - wick
    # volume correlated with absolute return magnitude
    base_vol = rng.lognormal(mean=2.5, sigma=0.4, size=n_bars)
    volume = base_vol * (1 + 50 * np.abs(returns))

    end_ms = int(time.time() * 1000) // step_ms * step_ms
    start_ms = end_ms - n_bars * step_ms
    ts = pd.to_datetime(np.arange(start_ms, end_ms, step_ms), unit="ms", utc=True)

    return pd.DataFrame({
        "open": open_, "high": high, "low": low, "close": close, "volume": volume,
    }, index=pd.Index(ts, name="timestamp"))


def load_ohlcv(symbol: str = "BTCUSDT", interval: str = "1m", bars: int = 1000,
               cache_dir: str = "data", force_synthetic: bool = False) -> FetchResult:
    """Return OHLCV. Tries Binance live, falls back to cached CSV, then synthetic."""
    os.makedirs(cache_dir, exist_ok=True)
    cache_path = os.path.join(cache_dir, f"{symbol}_{interval}.csv")

    if not force_synthetic:
        df = _binance_klines(symbol, interval, bars)
        if df is not None:
            df.to_csv(cache_path)
            return FetchResult(df=df.tail(bars), source="binance", symbol=symbol, interval=interval)

        if os.path.exists(cache_path):
            df = pd.read_csv(cache_path, index_col="timestamp", parse_dates=True)
            if len(df) >= bars // 2:
                return FetchResult(df=df.tail(bars), source="cache", symbol=symbol, interval=interval)

    df = _synthetic_ohlcv(interval, bars)
    df.to_csv(cache_path)
    return FetchResult(df=df, source="synthetic", symbol=symbol, interval=interval)


if __name__ == "__main__":
    for interval in ("1m", "5m"):
        res = load_ohlcv(interval=interval, bars=2000)
        print(f"{res.symbol} {res.interval}: {len(res.df)} bars  source={res.source}")
        print(res.df.tail(3))
